version: '3.7'
services:
  db:
    image: postgres
    container_name: ngdatabase
    environment:
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432-5432'
  api:
    build: ./teste
    container_name: api-teste
    ports:
      - '3000:3000'
    depends_on:
      - db
